name: Deploy .NET API to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout mã nguồn từ GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup .NET 8 SDK
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3. Publish ứng dụng API (FPTStella.API)
      - name: Publish .NET project
        run: dotnet publish FPTStella/FPTStella.API/FPTStella.API.csproj -c Release -o ./publish

      # 4. Sao chép các tệp đã publish lên VPS
      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "publish/*"
          target: "${{ secrets.REMOTE_TARGET }}"
          rm: true

      # 5. Khởi động lại dịch vụ trên VPS
      - name: Restart service on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            sudo systemctl restart cicdsample
            sudo systemctl status cicdsample
